import { useRouter } from 'expo-router';
import { Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';

import { themes } from '@/theme/colors';
import { useTheme, type ThemeId } from '@/theme/ThemeContext';
import Icon from './home/Icon';

const themeLabels: Record<ThemeId, string> = { light: 'Açık', sepia: 'Sepya', dark: 'Koyu', warm: 'Sıcak', amber_night: 'Amber Gece' };
const themeIds = Object.keys(themes) as ThemeId[];

export default function SettingsScreen() {
  const router = useRouter();
  const { theme, themeId, setThemeId } = useTheme();

  return <SafeAreaView style={[styles.safe, { backgroundColor: theme.main }]}><View style={styles.content}><View style={styles.header}><Pressable onPress={() => router.back()} style={[styles.back, { backgroundColor: theme.cardBg, borderColor: theme.cardBorder }]}><Icon name="chevron.right" size={18} color={theme.textPrimary} /></Pressable><Text style={[styles.title, { color: theme.textPrimary }]}>Ayarlar</Text><View style={styles.headerSpacer} /></View><View style={[styles.section, { backgroundColor: theme.cardBg, borderColor: theme.cardBorder }]}><Text style={[styles.sectionTitle, { color: theme.textPrimary }]}>Görünüm</Text><Text style={[styles.sectionDescription, { color: theme.textSecondary }]}>Uygulamanın renk temasını seçin.</Text><View style={styles.themeList}>{themeIds.map((id) => { const selected = id === themeId; const optionTheme = themes[id]; return <Pressable key={id} onPress={() => setThemeId(id)} style={[styles.themeButton, { backgroundColor: selected ? optionTheme.accentLight : theme.secondary, borderColor: selected ? theme.accent : theme.cardBorder }]}><View style={[styles.swatch, { backgroundColor: optionTheme.accent }]} /><Text style={[styles.themeLabel, { color: theme.textPrimary }]}>{themeLabels[id]}</Text><View style={[styles.radio, { borderColor: selected ? theme.accent : theme.textMuted }]}>{selected && <View style={[styles.radioDot, { backgroundColor: theme.accent }]} />}</View></Pressable>; })}</View></View><Pressable onPress={() => router.push('/font-lab')} style={[styles.fontLabButton, { backgroundColor: theme.accentLight, borderColor: theme.accentSoft }]}><View style={styles.fontLabCopy}><Text style={[styles.fontLabTitle, { color: theme.textPrimary }]}>Font denemeleri</Text><Text style={[styles.fontLabDescription, { color: theme.textSecondary }]}>Arapça metinleri farklı ailelerle karşılaştırın.</Text></View><Icon name="chevron.right" size={18} color={theme.accent} /></Pressable><Pressable onPress={() => router.push('/arabic-font-lab')} style={[styles.fontLabButton, { backgroundColor: theme.accentLight, borderColor: theme.accentSoft }]}><View style={styles.fontLabCopy}><Text style={[styles.fontLabTitle, { color: theme.textPrimary }]}>Arapça.Fontlar</Text><Text style={[styles.fontLabDescription, { color: theme.textSecondary }]}>İndirilen Arapça fontlarını ayrı karşılaştırın.</Text></View><Icon name="chevron.right" size={18} color={theme.accent} /></Pressable><Pressable onPress={() => router.push('/font-lab-v2' as never)} style={[styles.fontLabButton, { backgroundColor: theme.accentLight, borderColor: theme.accentSoft }]}><View style={styles.fontLabCopy}><Text style={[styles.fontLabTitle, { color: theme.textPrimary }]}>Lab V2</Text><Text style={[styles.fontLabDescription, { color: theme.textSecondary }]}>Uthmanic Bazzi V20 font denemesi.</Text></View><Icon name="chevron.right" size={18} color={theme.accent} /></Pressable></View></SafeAreaView>;
}

const styles = StyleSheet.create({ safe: { flex: 1 }, content: { gap: 18, padding: 20 }, header: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between' }, back: { alignItems: 'center', borderRadius: 10, borderWidth: 1, height: 38, justifyContent: 'center', transform: [{ rotate: '180deg' }], width: 38 }, headerSpacer: { width: 38 }, title: { fontFamily: 'Lora_700Bold', fontSize: 18 }, section: { borderRadius: 18, borderWidth: 1, gap: 7, padding: 16 }, sectionTitle: { fontFamily: 'Lora_700Bold', fontSize: 15 }, sectionDescription: { fontFamily: 'PlusJakartaSans_400Regular', fontSize: 11, marginBottom: 8 }, themeList: { gap: 9 }, themeButton: { alignItems: 'center', borderRadius: 12, borderWidth: 1, flexDirection: 'row', gap: 10, padding: 12 }, swatch: { borderRadius: 12, height: 24, width: 24 }, themeLabel: { flex: 1, fontFamily: 'PlusJakartaSans_600SemiBold', fontSize: 13 }, radio: { alignItems: 'center', borderRadius: 10, borderWidth: 1.5, height: 19, justifyContent: 'center', width: 19 }, radioDot: { borderRadius: 5, height: 9, width: 9 }, fontLabButton: { alignItems: 'center', borderRadius: 14, borderWidth: 1, flexDirection: 'row', padding: 15 }, fontLabCopy: { flex: 1, gap: 3 }, fontLabTitle: { fontFamily: 'PlusJakartaSans_600SemiBold', fontSize: 13 }, fontLabDescription: { fontFamily: 'PlusJakartaSans_400Regular', fontSize: 10 } });